### ISSUE TITLE
What bugs does this fix?

### ISSUE THREAD

**Issue by Espionage724** [GalaxyMaster2/HitsoundTweaks#1]
> ...and fixes several base game bugs

What bugs specifically are fixed by this mod?

**Comment by GalaxyMaster2** [comment]
More details can be found in the harmony patches, but here's a summary:

- Hitsounds being skipped with too many notes on screen
- Incorrect timing compensation for random hitsound pitch
- Inaccurate and inconsistent hitsound timing synchronization with the song
- Hitsounds being skipped for notes spawned out of order (mostly relevant for chains and NoodleExtensions maps)
